### ISSUE TITLE
change colour of cross mark as it is not visiable

### ISSUE THREAD

**Issue by mannar-1** [RishabhhG/Truck-vistariya#13]
change colour of cross mark as it is not visiable
![image](https://github.com/user-attachments/assets/a970865a-40a0-4ac9-a4ee-24c29f43338a)
i want to make it visable and make it look better , please assign it to me as part of hacktoberfest.

**Comment by RishabhhG** [comment]
make the required changes.

**Comment by mannar-1** [comment]
![image](https://github.com/user-attachments/assets/ab4fc8dd-8e15-400b-9c86-9a345b00736d)
i have made changes push code into mannar-1:cross_mark_color
and raised mr please check and approve or give suggestions
