### ISSUE TITLE
selected field disappers in create shipment 

### ISSUE THREAD

**Issue by Dheeraj-Bangera** [RishabhhG/Truck-vistariya#27]
![image](https://github.com/user-attachments/assets/dcf28f83-5aba-4ee6-8cd4-8a9a28fc7f8b)
![image](https://github.com/user-attachments/assets/800d587d-b38b-47cb-91d3-9d446ffc9eda)
fix the dropdown data in formdata is correct fix the ui

**Comment by AmanS369** [comment]
I have solved this issue , kindly check my PR
